<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "casa_timeline"
 *
 * Auto generated by Extension Builder 2021-03-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Timeline',
    'description' => 'Timeline with events. Each event has its own gallery.',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-12.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
